import { Injectable } from '@angular/core';
import { IGroup, IGroupUser, IUser } from '../models/group';
import {
  IAttachment,
  IGroupTask,
  ITask,
  ITaskHistory,
  ITaskTemplate,
  ITaskTemplateChild,
} from '../models/task';

// insert nums cntl+alt+n
//duplicate line ctnl+alt + up/down arrow
//row edit shift+alt+ up/down arrow

@Injectable({
  providedIn: 'root',
})
export class TestDataService {
  constructor() {}

  //Group Models
  getUsers(): IUser[] {
    return [
      {
        id: 1,
        firstName: 'Dan',
        lastName: 'Stewart',
        isAdmin: true,
        userName: 'dstewart',
      },
      {
        id: 2,
        firstName: 'Heidi',
        lastName: 'Stewart',
        isAdmin: true,
        userName: 'hstewart',
      },
      {
        id: 3,
        firstName: 'Abe',
        lastName: 'Stewart',
        isAdmin: true,
        userName: 'astewart',
      },
    ];
  }

  getGroups(): IGroup[] {
    return [
      { id: 1, groupName: 'Personal', groupType: 'personal', ownerUserId: 1 },
      { id: 2, groupName: 'Personal', groupType: 'personal', ownerUserId: 2 },
      { id: 3, groupName: 'Personal', groupType: 'personal', ownerUserId: 3 },
      { id: 4, groupName: 'Family', groupType: 'team', ownerUserId: 1 },
      { id: 5, groupName: 'Waukee Schools', groupType: 'org', ownerUserId: 1 },
      { id: 6, groupName: 'Full Family', groupType: 'org', ownerUserId: 1 },
    ];
  }

  getGroupUsers(): IGroupUser[] {
    return [
      { id: 1, groupId: 1, userId: 1 },
      { id: 2, groupId: 2, userId: 2 },
      { id: 3, groupId: 3, userId: 3 },
      { id: 4, groupId: 4, userId: 1 },
      { id: 5, groupId: 4, userId: 2 },
      { id: 6, groupId: 4, userId: 3 },
      { id: 7, groupId: 5, userId: 1 },
      { id: 8, groupId: 5, userId: 2 },
      { id: 9, groupId: 5, userId: 3 },
      { id: 10, groupId: 1, userId: 1 },
    ];
  }

  //Task Models
  getGroupTasks(): IGroupTask[] {
    return [
      {
        id: 1,
        groupId: 1,
        taskId: 1,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: false,
        archive: false,
      },
      {
        id: 2,
        groupId: 2,
        taskId: 2,
        claimingUserId: 1,
        creatingUserId: 2,
        creatingUserReviewClosed: false,
        archive: false,
      },
      {
        id: 3,
        groupId: 1,
        taskId: 3,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: false,
        archive: false,
      },
      {
        id: 4,
        groupId: 1,
        taskId: 4,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: false,
        archive: false,
      },
      {
        id: 5,
        groupId: 4,
        taskId: 5,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: true,
        archive: false,
      },
      {
        id: 6,
        groupId: 4,
        taskId: 6,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: false,
        archive: false,
      },
      {
        id: 7,
        groupId: 5,
        taskId: 7,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: false,
        archive: false,
      },
      {
        id: 8,
        groupId: 5,
        taskId: 8,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: false,
        archive: false,
      },
      {
        id: 9,
        groupId: 5,
        taskId: 9,
        claimingUserId: 1,
        creatingUserId: 1,
        creatingUserReviewClosed: false,
        archive: false,
      },
    ];
  }

  getTasks(): ITask[] {
    return [
      {
        id: 1,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 0,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 1,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 1,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 2,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 2,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 3,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 3,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 4,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 4,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 5,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 5,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 6,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 6,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 7,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 7,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 8,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 8,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
      {
        id: 9,
        name: '',
        details: '',
        originalPosition: '',
        originalPriority: '',
        currentPriority: '',
        currentPosition: 5,
        currentPositionOrder: 9,
        notes: '',
        taskTemplateId: undefined,
        taskCompleted: false,
        finalResponse: '',
        qnaTaskTemplateId: undefined,
        repeatTask: false,
        repeatDuration: '',
        flowDefinitionId: undefined,
        flowRun: false,
        aggraTask: false,
        aggraCount: 0,
      },
    ];
  }

  //insert nums cntl+alt+n
  //duplicate line shift+alt + up/down arrow
  //row edit cntl+alt+ up/down arrow
  //clipboard history: cntl+shift+V

  getTaskHistory(): ITaskHistory[] {
    return [
      {
        id: 1,
        taskId: 0,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 1,
        taskId: 1,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 2,
        taskId: 2,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 3,
        taskId: 3,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 4,
        taskId: 4,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 5,
        taskId: 5,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 6,
        taskId: 6,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 7,
        taskId: 7,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 8,
        taskId: 8,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
      {
        id: 9,
        taskId: 9,
        historyTypeId: 1,
        historyTypeName: 'Fwd',
        historyChangeText: 'Fwd1 > Fwd2',
        historyChangeDeciText: 'Fwd2 > Fwd3',
        historyChangeCentiText: 'Fwdd3 > Fwd4',
        historyChangeMilleText: 'Fwd4 > Fwd5',
        historyChangeMicroText: 'Fwd5 > Fwd6',
      },
    ];
  }

  getAttachments(): IAttachment[] {
    return [
      {
        id: 1,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 2,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 3,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 4,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 5,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 6,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 7,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 8,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
      {
        id: 9,
        taskId: 1,
        attachementItemName: 'File1.xls',
        attachementItem: 'some text encoding',
      },
    ];
  }

  getTaskTemplates(): ITaskTemplate[] {
    return [
      { id: 1, taskId: 1, name: '', type: '' },
      { id: 2, taskId: 1, name: '', type: '' },
      { id: 3, taskId: 1, name: '', type: '' },
      { id: 4, taskId: 1, name: '', type: '' },
      { id: 5, taskId: 1, name: '', type: '' },
      { id: 6, taskId: 1, name: '', type: '' },
      { id: 7, taskId: 1, name: '', type: '' },
      { id: 8, taskId: 1, name: '', type: '' },
      { id: 9, taskId: 1, name: '', type: '' },
    ];
  }

  getITaskTemplateChildren(): ITaskTemplateChild[] {
    return [
      { id: 1, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 2, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 3, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 4, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 5, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 6, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 7, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 8, taskId: 1, name: '', taskTemplateId: 1 },
      { id: 9, taskId: 1, name: '', taskTemplateId: 1 },
    ];
  }
}
